# Generated by Django 5.0 on 2024-01-18 12:31

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
